// <auto-generated />
namespace ProyectoFinalCadenaHotelera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creacion_tablas_iniciales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creacion_tablas_iniciales));
        
        string IMigrationMetadata.Id
        {
            get { return "202011302221535_Creacion_tablas_iniciales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
